/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.PolitecnicoMalaga.Bucles3;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        /*
         * Muestra los primeros 10 múltiplos de un número entero recogido desde el teclado, mediante un
         * bucle do-while.
         *
         * * @Author: Noelia Segovia
         */
        Scanner teclado = new Scanner(System.in);

        int num, multiplo, i = 1;

        System.out.println("Introduce un número entero: ");
        num = teclado.nextInt();

        do {
            System.out.println(multiplo = (num * i));
            i = i + 1;
        } while (i <= 10);
    }
}
