/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Variables2;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {

        Scanner teclado = new Scanner(System.in);

        int x, y;
        int suma, resta, div, mult;

        System.out.println("Introduzca el número x: ");
        x = teclado.nextInt();

        System.out.println("Introduzca el número y: ");
        y = teclado.nextInt();

        suma = x + y;
        resta = x - y;
        div = x / y;
        mult = x * y;

        System.out.println("El resultado de sumar los números es: " + suma);
        System.out.println("El resultado de restar los números es: " + resta);
        System.out.println("El resultado de dividir los números es: " + div);
        System.out.println("El resultado de multiplicar los números es: " + mult);
    }

}
