/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.PolitecnicoMalaga.Bucles5;

public class App {
    public static void main(String[] args) {
        /*
         * Muestra una cuenta atrás desde 20 a 1 por pantalla, usando un bucle while.
         *
         * @Author: Noelia Segovia
         */

        int i= 20;
        while (i>=1){
            System.out.println(i);
            i=i-1;
        }
    }
}
