/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Variables6;

import java.util.Scanner;

public class App {

/**
 * Escribe un programa que calcule el total de una factura a partir de la base
 * imponible (precio sin IVA).Todos los datos se leerán desde el teclado
 *
 * @author noelia
     * @param args
 */
    public static void main(String[] args) {

        Scanner teclado = new Scanner(System.in);

        double baseImp, totalFact, IVA;

        System.out.println("Introduce la base imponible: ");
        baseImp = teclado.nextDouble();

        System.out.println("¿Qué tipo de gravamen corresponde a esta factura? (4,10 o 21)");
        IVA = teclado.nextDouble();
        
        totalFact = baseImp * (1*IVA);
        
        System.out.println("Total factura: " + totalFact);
    }
}
