/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Variables3;

public class App {
/**
 * Crea la variable nombre y asígnale tu nombre completo mediante un literal.
 * Muestra su valor por pantalla.
 *
 * @author noelia
 */
    public static void main(String[] args) {

        String nombre = "Noelia Segovia Sanchez";

        System.out.println("El nombre completo es: " + nombre);

    }
}
