/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Condicionales3;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Scanner teclado = new Scanner(System.in);

        int horasTrabajadas, ordinarias = 0, extras = 0, salario;

        System.out.println("Introduce el número de horas trabajadas:");
        horasTrabajadas = teclado.nextInt();

        if (horasTrabajadas <= 40) {
            ordinarias = horasTrabajadas * 15;
        }
        if (horasTrabajadas > 40) {
            extras = (horasTrabajadas - 40) * 20;
        }

        salario = ordinarias + extras;
        System.out.println("El salario es de " + salario + "€");
        
        teclado.close();
    }
}
