/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Condicionales4;

import java.util.Scanner;

public class App {
 
    public static void main(String[] args) {
        Scanner teclado = new Scanner(System.in);

        double nota1, nota2, nota3, nota;

        System.out.println("Introduce la nota del 1er trimestre:");
        nota1 = teclado.nextInt();

        System.out.println("Introduce la nota del 2do trimestre:");
        nota2 = teclado.nextInt();

        System.out.println("Introduce la nota del 3er trimestre:");
        nota3 = teclado.nextInt();
        
        nota = (nota1 + nota2 + nota3) /3;

        if (nota >= 0 && nota < 5) {
            System.out.println("Nota académica: " + nota + "(Insuficiente)");
        } else if (nota >= 5 && nota < 6) {
            System.out.println("Nota académica: " + nota + "(Suficiente)");
        } else if (nota >= 6 && nota < 7) {
            System.out.println("Nota académica: " + nota + "(Bien)");
        } else if (nota >= 7 && nota < 8.5) {
            System.out.println("Nota académica: " + nota + "(Notable)");
        } else if (nota >= 8.5 && nota <= 10) {
            System.out.println("Nota académica: " + Math.round(nota) + "(Sobresaliente)");
        }
        teclado.close();
    }
}
