/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Variables5;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {

        Scanner teclado = new Scanner(System.in);

        String nombre, dir;
        int telefono;

        System.out.println("Introduce tu nombre: ");
        nombre = teclado.nextLine();

        System.out.println("Introduce tu dirección: ");
        dir = teclado.nextLine();

        System.out.println("Introduce tu teléfono: ");
        telefono = teclado.nextInt();

        System.out.println("Nombre: " + nombre);
        System.out.println("Dirección: " + dir);
        System.out.println("Teléfono: " + telefono);
    }

}
