/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.PolitecnicoMalaga.Bucles1;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        /*
         *Muestra los primeros 10 múltiplos de un número entero recogido desde el teclado, mediante un
         *bucle for.
         * @Author: Noelia Segovia
         * */
        Scanner teclado = new Scanner(System.in);

        int num;

        System.out.println("Introduce un número: ");
        num = teclado.nextInt();

        for (int i = 1; i <= 10; i++) {
            System.out.println(num * i);
        }
    }
}
