/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.PolitecnicoMalaga.Bucles6;

public class App {
    public static void main(String[] args) {
        /*
         * Muestra una cuenta atrás desde 20 a 1 por pantalla, usando un bucle do while.
         *
         * @Author: Noelia Segovia
         */

        int i = 21;

        do {
            i = i-1;
            System.out.println(i);

        } while (i > 1);
    }
}
