/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.PolitecnicoMalaga.Bucles4;

public class App {
    public static void main(String[] args) {
        /*
         * Muestra una cuenta atrás desde 20 a 1 por pantalla, usando un bucle for.
         *
         * @Author: Noelia Segovia
         */

        for (int i = 20; i >= 1; i--) {
            System.out.println(i);
        }
    }
}
